### PR TITLE
Add OS check to PostBuild property group.

### PR DESCRIPTION
**Pull request by dlech**
This prevents an error when building on Linux/Mac.

### CODE REVIEW

**Comment by dlech** [comment]
Hmm. It looks like the post build is in there twice already. Once with this fix and once without. Maybe I've got something wrong here. Don't merge yet.

**Comment by dlech** [comment]
OK. It looks like for some reason, this got duplicated when you upgrade to VS2013. I've updated the pull request to remove the duplicate section. I've tested in VS2013 to verify that the PostBuild is there, but ignored by Mono. Merge away.

**Comment by dlech** [comment]
https://github.com/dlech/KeeFox/commit/9dd060ad48aa8174fa609e7a58f55008b93c58fb#diff-7fc46b185553786185448ec2789370fa

Here's the commit in case you are interested.

**Comment by luckyrat** [comment]
Weird. I wonder if that was a git merge glitch or VS upgrade glitch, probably won't ever know.

**Pull request merged**
