### PR TITLE
Change line endings in chrome.manifest to make .gitattributes happy.

### PR DESCRIPTION
**Pull request by dlech**
I'm not sure if this is what you want, but now that there is a .gitattributes file, git is complaining that the chrome.manifest file has changed.

### CODE REVIEW

**Comment by luckyrat** [comment]
Well, I think so, but it is weird that it's complained at you and not me. I thought the .gitattributes file was supposed to normalise all the line endings as of when I enabled it. What platform are you editing on?

**Comment by dlech** [comment]
I'm on Linux. I was wondering if you used `git update-index --assume-unchanged` or something like that to caused the file to be ignored for you locally.

**Comment by luckyrat** [comment]
Ooooh that sounds likely. It was a while back now but I do have a vague memory of having to click "Assume unchanged" once when there appeared to be no other possible way for me to proceed. I honestly have no idea what that did but it made all of TortoiseGit's error messages go away and I'd almost entirely forgotten about the whole ordeal.

I don't remember which file(s) I had to do that on - maybe just this one. Do you think you'd notice if others were affected in the same way?

As far as command-line git goes, I'm lost once it gets much more complicated than commit, push and pull. If TortoiseGit has essentially run that update-index command has it done something permanent to my local index or will it just fix itself when I pull this change?

**Comment by dlech** [comment]
The `git update-index` help says

> Git will fail (gracefully) in case it needs to modify this file in the index e.g. when merging in a commit; thus, in case the assumed-untracked file is changed upstream, you will need to handle the situation manually.

So, if you merge this commit, it sounds like you will be forced to deal with it.

That was the only file like that, so I assume all the rest had their line endings normalized and you don't have any other locally ignored files.

**Comment by luckyrat** [comment]
Well it seems OK. The change pulled to my repo with no problem and I also found an option to "show ignore local changes flagged files" which was empty before and after the pull so I'm no clearer on what's been going on but at least there are no errors :-)

**Pull request merged**
