### PR TITLE
Issue389

### PR DESCRIPTION
**Pull request by dlech**
I've tested this in both Firefox and Thunderbird. It even handles canceling/undoing the disabling or uninstalling.

### CODE REVIEW

**Comment by luckyrat** [comment]
Great. It'll be awesome to get this fixed up. I'm just wondering if there's a reason you've done it on the keefox_win object instead of keefox_org? I would have thought that add-on related code should have no problem executing before the main window starts loading and we probably don't want it running once per window.

Silly me for thinking a bool had 2 values! I wonder how many other prefs in Firefox are used in that way - I'll look out for it in future.

PS: It seems odd that this includes the commits from earlier pull requests, but github still seems happy to merge so I guess it'll work itself out anyway.

**Comment by dlech** [comment]
> I'm just wondering if there's a reason you've done it on the keefox_win object instead of keefox_org?

No reason other that that was the way the example did it. I will try it in `keefox_org`.

> It seems odd that this includes the commits from earlier pull requests

Normally I wouldn't do this, but since Thunderbird was broken, I had to develop it on top of the other commits and I didn't bother cherrypicking to a separate branch.

**Comment by dlech** [comment]
I've pushed a new commit so that everything is now in `keefox_org`. Also factored out some duplicate code and rebased on master.

**Comment by luckyrat** [comment]
Looks good. Thanks.

> Normally I wouldn't do this, but since Thunderbird was broken, I had to develop it on top of the other commits and I didn't bother cherrypicking to a separate branch.

Ah, makes sense now then. No problem :-)

**Pull request merged**
